<!DOCTYPE html>
<?php

require_once $_SERVER['DOCUMENT_ROOT'] . '/php/constants.php';
require_once PHPROOT . '/renderer.php';
require_once PHPROOT . '/js-lib.php';

?>
<html>
	<head>
		<title></title>

		<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>

<!-- 		<script src="/js/MathJax-2.7.3/MathJax.js"></script>
		<script>
			
			MathJax.Hub.Config({
			  tex2jax: {
			    inlineMath: [ ['$','$'], ['\\(','\\)'] ]
			  }
			});

		</script> -->

		<link rel="stylesheet" href="/css/main.css">

		<style>
			
			.main-article {
				clear: both;
			}
			.theorem-image {
				float: left;
			}

			mjx-container {
				outline: none;
			}

		</style>

	</head>
	<body>
		<?php include('header.phtml');?>
		<div class="container">
			<main>
				<?php foreach($theorems as $theorem): ?>

				<article class="main-article">
					<h4 class="article-heading"><?= @$theorem['theorem_title']; ?></h4>
					<section>
						<img class="theorem-image" src="<?=@$theorem['theorem_image_src'];?>">
						<p>
							<?=@$theorem['theorem_content'];?>
						</p>
					</section>
				</article>

				<?php endforeach; ?>
			</main>
		</div>
	</body>
</html>