<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ganymede</title>
  <link rel="stylesheet" href="../css/definitions.css">
</head>
<body>
  <div class="page">
    <?php include('header.phtml')?>
      <div class="def-content">
        <div><a href="/" id="return-btn"></a></div> <!-- Сделать кнопку -->
        <h1>Определения</h1>
        <div class="def-content__sections">
          <div class="def-content__sections-wrapper">
            <a class="def-content__section def-content__section-1" href="#">
              <h2>Понятия</h2>
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic distinctio inventore exercitationem saepe, expedita beatae quidem reprehenderit omnis quae laboriosam non sit odio, et repellat est assumenda sunt nobis quos!</p>
            </a>
            <a class="def-content__section def-content__section-2" href="#">
              <h2>Аксиомы</h2>
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic distinctio inventore exercitationem saepe, expedita beatae quidem reprehenderit omnis quae laboriosam non sit odio, et repellat est assumenda sunt nobis quos!</p>
            </a>
            <a class="def-content__section def-content__section-3" href="#">
              <h2>Теоремы</h2>
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic distinctio inventore exercitationem saepe, expedita beatae quidem reprehenderit omnis quae laboriosam non sit odio, et repellat est assumenda sunt nobis quos!</p>
            </a>
            <a class="def-content__section def-content__section-4" href="#">
              <h2>Фигуры</h2>
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Hic distinctio inventore exercitationem saepe, expedita beatae quidem reprehenderit omnis quae laboriosam non sit odio, et repellat est assumenda sunt nobis quos!</p>
          </a>
          </div>
        </div>
      </div>
    <?php include('footer.phtml')?>
  </div>
</body>
</html>