<head>
  <link rel="stylesheet" href="../css/footer.css">
</head>
<body>
  <footer class="footer">
    <div class="footer__social-media">
      <p>Наши соцсети</p>
      <div class="footer__social-media-icons">
        <a class="footer__icon footer__vk" href="#"></a>
        <a class="footer__icon footer__tg" href="#"></a>
        <a class="footer__icon footer__im" href="#"></a>
        <a class="footer__icon footer__yt" href="#"></a>
      </div>
    </div>
    <p class="footer__creds">Ganymede — сайт для изучения геометрии! © 2021</p>
  </footer>
</body>