<head>
  <link rel="stylesheet" href="../css/header.css">
</head>
<body>
  <header class="header">
    <div class="header__logo-wrapper">
      <a href="/" ><img src="../images/logo.png" alt="" width="178" height="35" id="header__logo"></a>
    </div>
    <img src="../images/search-icon.png" alt="" class="header__search-icon" width="19" height="20">
    <div class="header__search">
      <img src="../images/search-icon.png" alt="" class="header__search-icon" width="16" height="16">
      <input type="text" placeholder="Введите поисковую фразу">
      <img src="../images/cancel-icon.png" alt="" id="header__cancel-icon" width="14" height="14">
    </div>
    <div>
      <a class="header__profile" href="/profile">
        <p>Профиль</p>
        <img src="../images/profile-icon.png" alt="" id="header__profile-icon" width="30" height="30">
        <img src="../images/profile-arrow.png" alt="" id="header__profile-arrow-icon" width="11" height="7">
      </a>
    </div>
  </header>
  <script src="../js/header.js"></script>
</body>