<!DOCTYPE html>
<?php

require_once $_SERVER['DOCUMENT_ROOT'] . '/php/constants.php';
require_once PHPROOT . '/renderer.php';
require_once PHPROOT . '/formula-module.php';
require_once PHPROOT . '/js-lib.php';

$GLOBALS['PAGE_FORMULAS_COUNT'] = 50;
$GLOBALS['FORMULAS_COUNT'] = get_fgroups_count();


function get_fgroups_list_page($page_number) {

	global $FORMULAS_COUNT, $PAGE_FORMULAS_COUNT;

	$max_page_counts = ceil($FORMULAS_COUNT / $PAGE_FORMULAS_COUNT);

	$page_number = min($page_number, $max_page_counts);
	$page_index = $page_number - 1;

	$offset = $page_index * $PAGE_FORMULAS_COUNT;
	$count = $PAGE_FORMULAS_COUNT;

	$groups_list = get_fgroups_list($offset, $count);

	foreach ($groups_list as &$formula_data) {

		$query_data = ['group_id' => $formula_data['group_id']];

		$formula_data['group_href'] = '?' . http_build_query($query_data);


	}

	return $groups_list;

}

?>
<html>
	<head>
		<title></title>

		<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>

		<link rel="stylesheet" href="/css/main.css">

		<style>
			
			.main-article {
				clear: both;
			}
			.formula-image {
				float: left;
			}

			mjx-container {
				outline: none;
			}

		</style>

	</head>
	<body>
		<?php include('header.phtml');?>
		<div class="container">
			<main>
				<article class="main-article">
					<h2 class="article-heading">Формулы</h2>
					<section class="list-container">
						<?php

							$page_number = isset($_GET['page']) ? $_GET['page'] : 1;

							$formulas = get_fgroups_list_page($page_number);

						?>
						<?php foreach($formulas as $formula): ?>

						<div class="article-item">
							<a class="item-link" href="<?=@$formula['group_href']?>">
								<span class="link_title"><?=@$formula['group_title']?></span>
							</a>
						</div>		

						<?php endforeach; ?>
					</section>
				</article>
				<section class="flex flex-jc-center" style="margin: 1em 0;">
					Данный сайт не направлен на общее распространение данных, взятых с сайта&nbsp;<a href="https://calcs.su/html/calcs/math/area.html">calcs.su</a>. Только в целях защиты его как проекта по учебе.
				</section>
			</main>
		</div>
	</body>
</html>