<!DOCTYPE html>
<html>
	<head>
		<style>
			
			a.logo-anchor {
				text-decoration: none;
			}

			.logo-header {
				text-transform: uppercase;
				letter-spacing: 0.35em;	
				font-size: 1.2rem;
				color: rgba(5,99,103,1);
				text-shadow: 5px 4px 4px rgba(0, 0, 0, 0.25);
				font-family: Montserrat;
				font-weight: SemiBold;
			}

		</style>
	</head>
	<body>
		<a class="logo-anchor" href="/">
			<span class="logo-header">Ganymede</span>
		</a>
	</body>
</html>