<!DOCTYPE html>
<?php

require_once $_SERVER['DOCUMENT_ROOT'] . '/php/constants.php';
require_once PHPROOT . '/renderer.php';
require_once PHPROOT . '/theorem-module.php';
require_once PHPROOT . '/js-lib.php';

$GLOBALS['PAGE_THEOREMS_COUNT'] = 50;
$GLOBALS['THEOREMS_COUNT'] = get_theorems_count();


function get_theorems_list_page($page_number) {

	global $THEOREMS_COUNT, $PAGE_THEOREMS_COUNT;

	$max_page_counts = ceil($THEOREMS_COUNT / $PAGE_THEOREMS_COUNT);

	$page_number = min($page_number, $max_page_counts);
	$page_index = $page_number - 1;

	$offset = $page_index * $PAGE_THEOREMS_COUNT;
	$count = $PAGE_THEOREMS_COUNT;

	$theorems_list = get_theorems_list($offset, $count);

	foreach ($theorems_list as &$theorem_data) {

		$query_data = ['theorem_id' => $theorem_data['theorem_id']];

		$theorem_data['theorem_href'] = '?' . http_build_query($query_data);


	}

	return $theorems_list;

}

?>
<html>
	<head>
		<title></title>

		<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>

		<link rel="stylesheet" href="/css/main.css">

		<style>
			
			.main-article {
				clear: both;
			}
			.theorem-image {
				float: left;
			}

			mjx-container {
				outline: none;
			}

		</style>

	</head>
	<body>
		<?php include('header.phtml');?>
		<div class="container">
			<main>
				<article class="main-article">
					<h2 class="article-heading">Теоремы</h2>
					<section class="list-container">
						<?php

							$page_number = isset($_GET['page']) ? $_GET['page'] : 1;

							$theorems = get_theorems_list_page($page_number);

						?>
						<?php foreach($theorems as $theorem): ?>

						<div class="article-item">
							<a class="item-link" href="<?=@$theorem['theorem_href']?>">
								<span class="link_title"><?=@$theorem['theorem_title']?></span>
							</a>
						</div>		

						<?php endforeach; ?>
					</section>
				</article>
			</main>
		</div>
	</body>
</html>